### ISSUE TITLE
Hattie on v1.11 - Error removing hat with /hat

### ISSUE THREAD

**Issue by Ekzim** [ImagineCraft/Hattie#4]
This is with hattie v3.0
Equip block as hat using /hat.  Success.
Used /hat to remove block from being a hat. Fails.
Workaround: Can manually select hat in inventory screen and remove to place back in inventory.

[03:57:08] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f950f8e-b64d852 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

Generates error:

[04:25:11] [Server thread/INFO]: Ekzim issued server command: /hat
[04:25:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hat' in plugin Hattie v2.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-b64d852]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_11_R1.ItemStack.F(ItemStack.java:86) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at net.minecraft.server.v1_11_R1.ItemStack.setCount(ItemStack.java:814) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftItemStack.setAmount(CraftItemStack.java:153) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	at cz.sycha.hattie.Main.onCommand(Main.java:44) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-f950f8e-b64d852]
	... 15 more

**Comment by kriation** [comment]
I'll research, and push an update for this bug tonight.

**Comment by Ekzim** [comment]
This is with hattie 3.0

**Comment by kriation** [comment]
Reproduced the issue on 1.11 - Working on a fix.
